---
title: "The methylome in female adolescent Conduct Disorder: Neural pathomechanisms and Environmental Risk Factors"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Statistical analysis performed within the [femNAT-CD consortium](https://femnat-cd.eu)

**Main research aim**: Identify and systematically characterize differential methylation in females with conduct disorder. 

**Summary** of the work and **contributing authors** can be found in the [about](about.html) section. 

Full peer reviewed article is available [soon]() 

## Analysis Pipeline and Results

* [Preprocessing and Outcomes](01_Preprocessing.html)
* [Identification of differentially methylated sites](02_1_Main_LME.html)
* [Identification of differentially methylated regions](02_2_Main_DMR.html)
* [Follow up: SLITRK5 validation, Gene enrichment and environmental risk factor analysis](03_01_Posthoc_analyses_Gene_Enrichment.html)
* [Additional visualization of significant tags and regions](04_Plot_Results.html)


